version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - WEBSITE_EMAIL=${WEBSITE_EMAIL}
      - EMAIL_PASSWORD=${EMAIL_PASSWORD}
      - FORWARD_EMAIL=${FORWARD_EMAIL}
    restart: always
