name: CI/CD Pipeline for Bini Metal Website (Build & Package)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-package:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' # Use Node.js 20, matching your Dockerfile

      - name: Install dependencies
        run: npm ci # Use npm ci for clean installs in CI environments

      - name: Run ESLint
        run: npm run lint

      - name: Build Next.js application
        # The 'output: standalone' in next.config.mjs creates a self-contained folder
        # that can be deployed to any Node.js server.
        run: npm run build

      - name: Run tests (Optional)
        # Uncomment and replace with your actual test command if you have tests
        # run: npm test
        run: echo "No tests configured. Add 'npm test' or similar if you have tests."

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: nextjs-bini-metal-build
          path: |
            ./.next/standalone
            ./public
          retention-days: 7 # Keep artifacts for 7 days (adjust as needed)
